<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [ ]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a.ndim, b.ndim)
print(a.shape, b.shape)
# ========
print(a)
print(b)

2 2
(100, 100) (100, 100)
[[0.06824579 0.62234757 0.05916564 ... 0.09006201 0.94877757 0.34634978]
 [0.68713573 0.92433824 0.69476737 ... 0.53468308 0.33757823 0.76784297]
 [0.68108715 0.6870087  0.09782516 ... 0.86701773 0.86415526 0.88500839]
 ...
 [0.60217554 0.53767986 0.73649647 ... 0.23639045 0.22842713 0.96260107]
 [0.31501077 0.43924055 0.18255144 ... 0.60814672 0.04636355 0.08768198]
 [0.89385012 0.84849877 0.7395568  ... 0.47818287 0.44046094 0.13677865]]
[[0.4287263  0.87151896 0.17359533 ... 0.85942333 0.31005574 0.65141873]
 [0.7593426  0.58648469 0.25578337 ... 0.3111881  0.05701915 0.22742621]
 [0.28864031 0.17504696 0.82630445 ... 0.66741614 0.51988598 0.44765412]
 ...
 [0.51388125 0.50031084 0.11302234 ... 0.7059996  0.70455822 0.42912693]
 [0.41071688 0.43767522 0.34499178 ... 0.42085183 0.20372648 0.71195507]
 [0.24107447 0.63675    0.87447431 ... 0.23690728 0.54330321 0.0165583 ]]


In [ ]:
def mult(first, second):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    x, y = len(first[0]), len(second[0])
    result = [[0 for i in range(y)] for j in range(x)]
    for i in range(x):
        for j in range(y):
            for m in range(len(second[1])):
                result[i][m] += first[i][j] * second[j][m]
    return result

In [ ]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат\
    return a.dot(b)

np_mult(a, b)

array([[25.80956579, 26.14639097, 22.56765893, ..., 26.75977888,
        21.76258502, 24.35053492],
       [24.21544368, 23.00741523, 19.4515156 , ..., 26.84788556,
        20.75038339, 21.51209025],
       [26.63216282, 24.17119686, 22.73446979, ..., 26.6460271 ,
        20.89581095, 23.16248286],
       ...,
       [27.80559465, 25.44456369, 26.1742496 , ..., 28.24378433,
        22.72159347, 24.94167122],
       [25.99305263, 22.96982679, 20.67671714, ..., 26.37651048,
        20.42955425, 24.91814645],
       [27.79227863, 24.32803271, 23.88727825, ..., 28.9920497 ,
        23.3345235 , 25.72101592]])

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1 s, sys: 542 µs, total: 1 s
Wall time: 1.01 s


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 0 ns, sys: 2.62 ms, total: 2.62 ms
Wall time: 5.76 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3237411167210666e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.11398108 0.397373   0.65525296] [0.29628533 0.13395634 0.58805093]


In [ ]:
def scalar_product(a,b):
    return sum(map(lambda x, y: x*y, a, b))

In [ ]:
sum(map(lambda x, y: x*y, a, b))

0.472323666563426

In [ ]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 267 µs, sys: 0 ns, total: 267 µs
Wall time: 273 µs
CPU times: user 81 µs, sys: 0 ns, total: 81 µs
Wall time: 85.1 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  d = np.diagonal(a,offset=0, axis1=0, axis2=1)
  return sum(d[d%2==0])

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 9, 3, 5, 7],
       [6, 6, 7, 9, 9],
       [4, 7, 1, 7, 9],
       [1, 9, 8, 6, 4],
       [3, 6, 1, 3, 8]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 70 µs, sys: 11 µs, total: 81 µs
Wall time: 86.5 µs


24

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​

​ 

In [ ]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    #param A: np.array[m,n]
    result = np.cumsum(A, axis=-1)
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 92 µs, sys: 15 µs, total: 107 µs
Wall time: 115 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [141]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
  Y=np.copy(X)
  Y[:,1::2] = a
  Y[:,0::2] = Y[:,0::2]**3
  Y[:,:]=Y[:,::-1]
  #Y[1]=Y[1][::-1]
  print(np.hstack((X, Y)))
  print(np.concatenate((X, Y), axis=1))
  return np.hstack((X, Y)) #
  #print(np.concatenate((X, Y), axis=1))

In [143]:
# X = np.array([i for i in range(1, 10, 2)])
X =  [[1,2,3,4,5],[1,2,3,4,5]]
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 1)
print(S2)

[[  1   2   3   4   5 125   1  27   1   1]
 [  1   2   3   4   5 125   1  27   1   1]]
[[  1   2   3   4   5 125   1  27   1   1]
 [  1   2   3   4   5 125   1  27   1   1]]
CPU times: user 579 µs, sys: 94 µs, total: 673 µs
Wall time: 679 µs
[[  1   2   3   4   5 125   1  27   1   1]
 [  1   2   3   4   5 125   1  27   1   1]]


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [176]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  return (np.array([x for x, y in itertools.groupby(a)]), \
          np.array([len(list(y)) for x, y in itertools.groupby(a)]))

In [177]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)
x, num

CPU times: user 45 µs, sys: 8 µs, total: 53 µs
Wall time: 55.6 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

In [144]:
def rle(inarray):
        """ run length encoding. Partial credit to R rle function. 
            Multi datatype arrays catered for including non Numpy
            returns: tuple (runlengths, startpositions, values) """
        ia = np.asarray(inarray)                # force numpy
        n = len(ia)
        if n == 0: 
            return (None, None, None)
        else:
            y = ia[1:] != ia[:-1]               # pairwise unequal (string safe)
            i = np.append(np.where(y), n - 1)   # must include last element posi
            z = np.diff(np.append(-1, i))       # run lengths
            p = np.cumsum(np.append(0, z))[:-1] # positions
            return(z, p, ia[i])

In [150]:
X

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [151]:
rle(X)

(array([1, 2, 2, 2, 2, 1, 2]),
 array([ 0,  1,  3,  5,  7,  9, 10]),
 array([1, 2, 3, 1, 5, 2, 3]))

In [160]:
import itertools
sv = [(x, list(y)) for x, y in itertools.groupby(X)]
#m1 = [x for x, y in itertools.groupby(X)]
m2 = [len(list(y)) for x, y in itertools.groupby(X)]
m2

[1, 2, 2, 2, 2, 1, 2]

In [154]:
list(itertools.groupby(X)

[(1, <itertools._grouper at 0x7f9dfc070350>),
 (2, <itertools._grouper at 0x7f9e00b6a7d0>),
 (3, <itertools._grouper at 0x7f9e00b6a690>),
 (1, <itertools._grouper at 0x7f9dfc1f5fd0>),
 (5, <itertools._grouper at 0x7f9dfeeb2c90>),
 (2, <itertools._grouper at 0x7f9dfc0f0f90>),
 (3, <itertools._grouper at 0x7f9dfc89e090>)]